export const NODE_TYPE_COLORS = {
  server:       "#22c55e",
  database:     "#3b82f6",
  api:          "#8b5cf6",
  client:       "#64748b",
  loadbalancer: "#f97316",
  cache:        "#eab308",
  queue:        "#ec4899",
  firewall:     "#ef4444",
  microservice: "#06b6d4",
};

export const NODE_TYPES = [
  "server",
  "database",
  "api",
  "client",
  "loadbalancer",
  "cache",
  "queue",
  "firewall",
  "microservice",
];

export const NODE_TYPE_LABELS = {
  server:       "Server",
  database:     "Database",
  api:          "API",
  client:       "Client",
  loadbalancer: "Load Balancer",
  cache:        "Cache",
  queue:        "Queue",
  firewall:     "Firewall",
  microservice: "Microservice",
};

export const FAILURE_COLORS = {
  failed:   "#ef4444",
  affected: "#f97316",
};

export const styles = {
  brandColor: "#6c63ff",
  input: {
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid #2a2a34",
    background: "#0f1114",
    color: "#eaeaf2",
    outline: "none",
    boxSizing: "border-box",
    fontSize: 13,
  },
  btn: {
    background: "#6c63ff",
    color: "#fff",
    border: "none",
    padding: "8px 10px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    textAlign: "center",
    fontSize: 14,
  },
  btnSmall: {
    background: "#6c63ff",
    color: "#fff",
    border: "none",
    padding: "6px 8px",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: 600,
  },
  btnDanger: {
    background: "#ef4444",
    color: "#fff",
    border: "none",
    padding: "8px 10px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    textAlign: "center",
    fontSize: 14,
  },
  ghostBtn: {
    background: "transparent",
    color: "#cfcfe0",
    border: "1px solid #2a2a34",
    padding: "8px 10px",
    borderRadius: 8,
    cursor: "pointer",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(2,6,10,0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  modal: {
    width: 360,
    background: "#12121a",
    padding: 18,
    borderRadius: 12,
    boxShadow: "0 8px 30px rgba(12,10,25,0.7)",
    border: "1px solid rgba(108,99,255,0.08)",
  },
};
