export const styles = {
  brandColor: "#6c63ff",
  input: {
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid #2a2a34",
    background: "#0f1114",
    color: "#eaeaf2",
    outline: "none",
    boxSizing: "border-box",
    fontSize: 13,
  },
  btn: {
    background: "#6c63ff",
    color: "#fff",
    border: "none",
    padding: "8px 10px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    textAlign: "center",
    fontSize: 14,
  },
  btnSmall: {
    background: "#6c63ff",
    color: "#fff",
    border: "none",
    padding: "6px 8px",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: 600,
  },
  ghostBtn: {
    background: "transparent",
    color: "#cfcfe0",
    border: "1px solid #2a2a34",
    padding: "8px 10px",
    borderRadius: 8,
    cursor: "pointer",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(2,6,10,0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  modal: {
    width: 360,
    background: "#12121a",
    padding: 18,
    borderRadius: 12,
    boxShadow: "0 8px 30px rgba(12,10,25,0.7)",
    border: "1px solid rgba(108,99,255,0.08)",
  },
};
